### ISSUE TITLE
App Crashing after integration MoEngage Flutter SDK: Failed resolution of: Lcom/moengage/core/Logger

### ISSUE THREAD

**Issue by jk-akshay-arora** [moengage/Flutter-SDK#12]
I followed the MoENgage integration documentation provided here: 

https://docs.moengage.com/docs/flutter-sdk-integration

After doing everything and trying to run the project, I am getting this error: Failed resolution of: Lcom/moengage/core/Logger

Stack Trace: 

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/moengage/core/Logger;
        at g.p.e.b.onAttachedToEngine(:18)
        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.add(:133)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(:44)
        at com.jaikisan.vendor_erp.MainActivity.configureFlutterEngine(:23)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(:181)
        at io.flutter.embedding.android.FlutterActivity.onCreate(:410)
        at com.jaikisan.vendor_erp.MainActivity.onCreate(:13)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.moengage.core.Logger" on path: DexPathList[[zip file "/data/app/com.jaikisan.vendor_erp-_oJZri788PTmgsWXyDsY1Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.jaikisan.vendor_erp-_oJZri788PTmgsWXyDsY1Q==/lib/x86, /data/app/com.jaikisan.vendor_erp-_oJZri788PTmgsWXyDsY1Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by jk-akshay-arora** [comment]
Turns out there was some issue with a custom wrapper I was using. Sorry my bad. Closing.
