### ISSUE TITLE
App crashes in Integration Validation test

### ISSUE THREAD

**Issue by rahuldange09** [moengage/Flutter-SDK#3]
I'm not able to test integration validation. As I open it in app. App crashes
Here are logs.

`time: 1587841829197
msg: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.moengage.integrationverifier.IntegrationVerificationActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2952)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3087)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1817)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at androidx.appcompat.app.h.v(Unknown Source:416)
	at androidx.appcompat.app.h.x(Unknown Source:4)
	at androidx.appcompat.app.h.c(Unknown Source:0)
	at androidx.appcompat.app.e.setContentView(Unknown Source:4)
	at com.moengage.integrationverifier.IntegrationVerificationActivity.onCreate(Unknown Source:5)
	at android.app.Activity.performCreate(Activity.java:7144)
	at android.app.Activity.performCreate(Activity.java:7135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2932)
	... 11 more`

**Comment by umangmoe** [comment]
The SDK expects that the app theme should extend `Theme.AppCompat` which does not seem to be the case here.
**_Solution:_**
Declare the below activity in your App's manifest file.

```xml
        <activity
        android:name="com.moengage.integrationverifier.IntegrationVerificationActivity"
        android:theme="@style/Theme.AppCompat"
        >

      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>

        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>

        <data
            android:host="integration"
            android:scheme="moengage"/>
      </intent-filter>
    </activity>
```

**Comment by umangmoe** [comment]
I hope the issue is fixed, given there is no response closing the issue.

**Comment by bhupendra-shiprocket** [comment]
Add android:theme in your application class with theme extending appcompact theme
```
<application
.
 android:theme="@style/AppThemeNoActionBar"
</application>
```
` <style name="AppThemeNoActionBar" parent="Theme.AppCompat.Light.NoActionBar">`
