### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.moengage.core.ConfigurationCache" on path: DexPathList

### ISSUE THREAD

**Issue by akshay-kapase** [moengage/Flutter-SDK#35]
Process: com.example.notification_test, PID: 17726
E/AndroidRuntime(17726): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/moengage/core/ConfigurationCache;
E/AndroidRuntime(17726): 	at com.moengage.flutter.MoEInitializer.initialize(MoEInitializer.java:16)
E/AndroidRuntime(17726): 	at com.example.notification_test.MyApplication.onCreate(MyApplication.kt:23)
E/AndroidRuntime(17726): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
E/AndroidRuntime(17726): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7039)
E/AndroidRuntime(17726): 	at android.app.ActivityThread.access$1600(ActivityThread.java:265)
E/AndroidRuntime(17726): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2042)
E/AndroidRuntime(17726): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17726): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(17726): 	at android.app.ActivityThread.main(ActivityThread.java:8087)
E/AndroidRuntime(17726): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17726): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/AndroidRuntime(17726): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

**Comment by umangmoe** [comment]
Please raise a ticket by writing to us at `support@moengage.com` with details like the SDK version used, your account information
