### ISSUE TITLE
[FATAL ERROR] - java.lang.NoSuchMethodError: No static method v(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by ariefwijaya** [moengage/Flutter-SDK#49]
I'm using this plugin in my project, when I run the apps, I got this fatal error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: id.chatalia.app, PID: 24669
    java.lang.NoSuchMethodError: No static method v(Ljava/lang/String;)V in class Lcom/moengage/core/internal/logger/Logger; or its super classes (declaration of 'com.moengage.core.internal.logger.Logger' appears in /data/app/~~QnrqfWsBTU98qPxH3X2cSg==/id.chatalia.app-K71CFalC-S4o4S3OxU7GEg==/base.apk!classes7.dex)
        at com.moengage.flutter.MoEInitializer$Companion.initialize(MoEInitializer.kt:21)
        at id.chatalia.app.MainApplication.onCreate(MainApplication.kt:21)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6832)
        at android.app.ActivityThread.access$1400(ActivityThread.java:244)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
       ```

Here is my implementation:
- **MainApplication.kt**
```
class MainApplication : FlutterApplication(){
    override fun onCreate() {
        super.onCreate()

      val moEngage = MoEngage.Builder(this, "L1429IVNIMU3BZT9I5PXCOD7")
              .configureNotificationMetaData(NotificationConfig(R.drawable.ic_stat_name, R.drawable.ic_launcher, R.color.ic_launcher_background, isMultipleNotificationInDrawerEnabled = true, isBuildingBackStackEnabled = false, isLargeIconDisplayEnabled = false))
            .configureFcm(FcmConfig(false))
              .enablePartnerIntegration(IntegrationPartner.SEGMENT)
              .configureLogs(LogConfig(LogLevel.VERBOSE, false));
      MoEInitializer.initialize(this, moEngage);
    }
}
```

- **android/app/build.gradle**
```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation platform('com.google.firebase:firebase-bom:30.4.1')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.android.support:multidex:1.0.3'

    //required by moengage
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation("androidx.core:core-ktx:1.9.0")
    implementation("androidx.appcompat:appcompat:1.5.1")
    implementation("androidx.lifecycle:lifecycle-process:2.5.1")
    implementation("com.moengage:moe-android-sdk:11.6.02")
}
```

**Comment by umangmoe** [comment]
Stale issue, closing.
Please reach out to `support@moengage.com` for any issues.
